accounts:
 - '305346208703'
 - 'junk_account'
exclude_accounts:
 - 'junk_account'
tasks:
 - name: lambda_errors
   region: 'all'
   account: 'all'
   role_name: 'cloudwatch-reader'
   metrics:
    - aws_namespace: "AWS/Lambda"
      aws_dimensions: ['FunctionName']
      aws_dimensions_select_regex:
        FunctionName: 'custodian-.*'
      aws_metric_name: 'Errors'
      aws_statistics: ['Maximum']
      range_seconds: 3600
      period_seconds: 300
      delay_seconds: 600
 - name: billing
   region: us-east-1
   metrics:
    - aws_namespace: "AWS/Billing"
      aws_dimensions: [Currency]
      aws_dimensions_select:
        Currency: [USD]
      aws_metric_name: EstimatedCharges
      aws_statistics: [Maximum]
      range_seconds: 86400
